# Generated by Django 6.0.7 on 2026-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_duda'),
    ]

    operations = [
        migrations.AddField(
            model_name='duda',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
